apiVersion: apps/v1
kind: Deployment
metadata:
  name: likhitha-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: likhitha
  template:
    metadata:
      labels:
        app: likhitha
    spec:
      containers:
      - name: likhitha-container
        image: bhanu3023/likhitha:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: likhitha-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: likhitha
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: likhitha-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: likhitha-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
