name: CI/CD for Java Maven Web Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 9
      uses: actions/setup-java@v2
      with:
        java-version: '9'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test

  deploy:
    name: Deploy to Tomcat
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Tomcat
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TOMCAT_HOST }}
        username: ${{ secrets.TOMCAT_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.TOMCAT_SSH_PORT }}
        script: |
          cd /path/to/your/webapp
          sudo systemctl stop tomcat.service
          rm -rf *
          scp -r $GITHUB_WORKSPACE/target/*.war ./
          sudo systemctl start tomcat.service
